=== mifos/1.4.x/application/src/main/resources/org/mifos/framework/util/resources/tabletag/type.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.aditi.com" xmlns="http://www.aditi.com"
	elementFormDefault="qualified ">
	
	<xs:element name="files">
		<xs:complexType>
			<xs:sequence>		
				<xs:element ref="filename" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="class" type="xs:string" />
			<xs:attribute name="resourcebundle" type="xs:string" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="filename">
		<xs:complexType>
			<xs:sequence>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" />
			<xs:attribute name="path" type="xs:string" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== mifos/1.4.x/application/src/main/resources/org/mifos/framework/util/resources/tabletag/type.xml
<?xml version="1.0" encoding="UTF-8"?>
<files class="org.mifos.xyz" name="client" resourcebundle="resource"
		xmlns="http://www.aditi.com" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:schemaLocation="http://www.aditi.com type.xsd ">
		<filename name="1" path="org/mifos/framework/util/resources/tabletag/CustomerClient.xml" />
		<filename name="2" path="org/mifos/framework/util/resources/tabletag/CustomerGroup.xml" />
		<filename name="3" path="org/mifos/framework/util/resources/tabletag/CustomerCenter.xml" />		
		<filename name="4" path="org/mifos/framework/util/resources/tabletag/LoanAccount.xml" />
		<filename name="5" path="org/mifos/framework/util/resources/tabletag/LoanAccountGroup.xml" />		
		<filename name="6" path="org/mifos/framework/util/resources/tabletag/ClientSavingAccount.xml" />
		<filename name="7" path="org/mifos/framework/util/resources/tabletag/GroupSavingAccount.xml" />
		<filename name="8" path="org/mifos/framework/util/resources/tabletag/CenterSavingAccount.xml" />
</files>
