=== mifos/1.4.x/application/src/main/resources/org/mifos/framework/util/resources/stateMachine/StateMachine.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.aditi.com" xmlns="http://www.aditi.com"
	elementFormDefault="qualified">
	<xs:element name="statemaps">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="stateConfiguration" maxOccurs="unbounded" minOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="stateConfiguration">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="state" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="configurationName" type="xs:string" use="required" />
			
		</xs:complexType>
	</xs:element>
	<xs:element name="state">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="statename" type="xs:string" />
				<xs:element name="stateid" type="xs:string" />
				<xs:element ref="possiblestates" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>

	</xs:element>
	<xs:element name="possiblestates">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="possiblestate" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="possiblestate">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="statename" type="xs:string" />
				<xs:element name="stateid" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== mifos/1.4.x/application/src/main/resources/org/mifos/framework/util/resources/stateMachine/StateMachine_saving.xml
<?xml version="1.0" encoding="UTF-8"?>
<statemaps xmlns="http://www.aditi.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.aditi.com StateMachine.xsd ">
	<stateConfiguration configurationName="configuration 1">
		<state>
			<statename>PartialApplication</statename>
			<stateid>13</stateid>
			<possiblestates>
			<possiblestate>
					<statename>PendingApproval</statename>
					<stateid>14</stateid>
			</possiblestate>
			<possiblestate>
				<statename>Cancel</statename>
				<stateid>15</stateid>
			</possiblestate>
			</possiblestates>
		</state>
		<state>
			<statename>Cancel</statename>
			<stateid>15</stateid>
		</state>		
		<state>
			<statename>PendingApproval</statename>
			<stateid>14</stateid>
			<possiblestates>
				<possiblestate>
					<statename>PartialApplication</statename>
					<stateid>13</stateid>
				</possiblestate>
				<possiblestate>
					<statename>Apporved</statename>
					<stateid>16</stateid>
				</possiblestate>
				<possiblestate>
					<statename>Cancel</statename>
					<stateid>15</stateid>
				</possiblestate>
			</possiblestates>
		</state>
		<state>
			<statename>Apporved</statename>
			<stateid>16</stateid>
			<possiblestates>
				<possiblestate>
					<statename>Inactive</statename>
					<stateid>18</stateid>
				</possiblestate>

			</possiblestates>
		</state>
		<state>
			<statename>Inactive</statename>
			<stateid>18</stateid>
			<possiblestates>
				<possiblestate>
					<statename>Apporved</statename>
					<stateid>16</stateid>
				</possiblestate>

			</possiblestates>
		</state>
	</stateConfiguration>
	
		<stateConfiguration configurationName="configuration 2">
		<state>
			<statename>PartialApplication</statename>
			<stateid>13</stateid>
			<possiblestates>
				<possiblestate>
					<statename>Apporved</statename>
					<stateid>16</stateid>
				</possiblestate>
				<possiblestate>
					<statename>Cancel</statename>
					<stateid>15</stateid>
				</possiblestate>
			</possiblestates>
		</state>
		<state>
			<statename>Cancel</statename>
			<stateid>15</stateid>
		</state>
		<state>
			<statename>Apporved</statename>
			<stateid>16</stateid>
			<possiblestates>
				<possiblestate>
					<statename>Inactive</statename>
					<stateid>18</stateid>
				</possiblestate>

			</possiblestates>
		</state>
		<state>
			<statename>Inactive</statename>
			<stateid>18</stateid>
			<possiblestates>
				<possiblestate>
					<statename>Apporved</statename>
					<stateid>16</stateid>
				</possiblestate>

			</possiblestates>
		</state>
	</stateConfiguration>
</statemaps>

=== mifos/1.4.x/application/src/main/resources/org/mifos/framework/util/resources/stateMachine/StateMachine_group.xml
<?xml version="1.0" encoding="UTF-8"?>
<statemaps xmlns="http://www.aditi.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.aditi.com StateMachine.xsd ">
	<stateConfiguration configurationName="configuration 1">
		<state>
			<statename>PartialApplication</statename>
			<stateid>7</stateid>
			<possiblestates>
				<possiblestate>
						<statename>PendingApproval</statename>
						<stateid>8</stateid>
				</possiblestate>
				<possiblestate>
					<statename>Cancel</statename>
					<stateid>11</stateid>
				</possiblestate>
			</possiblestates>
		</state>
		<state>
			<statename>Cancel</statename>
			<stateid>11</stateid>
			<possiblestates>
				<possiblestate>
						<statename>PartialApplication</statename>
						<stateid>7</stateid>
				</possiblestate>
			</possiblestates>
		</state>		
		<state>
			<statename>PendingApproval</statename>
			<stateid>8</stateid>
			<possiblestates>
				<possiblestate>
					<statename>PartialApplication</statename>
					<stateid>7</stateid>
				</possiblestate>
				<possiblestate>
					<statename>Apporved</statename>
					<stateid>9</stateid>
				</possiblestate>
				<possiblestate>
					<statename>Cancel</statename>
					<stateid>11</stateid>
				</possiblestate>
			</possiblestates>
		</state>
		<state>
			<statename>Apporved</statename>
			<stateid>9</stateid>
			<possiblestates>
				<possiblestate>
					<statename>OnHold</statename>
					<stateid>10</stateid>
				</possiblestate>
				<possiblestate>
					<statename>Closed</statename>
					<stateid>12</stateid>
				</possiblestate>
			</possiblestates>
		</state>
		<state>
			<statename>OnHold</statename>
			<stateid>10</stateid>
			<possiblestates>
				<possiblestate>
					<statename>Apporved</statename>
					<stateid>9</stateid>
				</possiblestate>
				<possiblestate>
					<statename>Closed</statename>
					<stateid>12</stateid>
				</possiblestate>
			</possiblestates>
		</state>
		<state>
			<statename>Closed</statename>
			<stateid>12</stateid>
		</state>
	</stateConfiguration>
	
		<stateConfiguration configurationName="configuration 2">
		<state>
			<statename>PartialApplication</statename>
			<stateid>7</stateid>
			<possiblestates>
				<possiblestate>
					<statename>Apporved</statename>
					<stateid>9</stateid>
				</possiblestate>
				<possiblestate>
					<statename>Cancel</statename>
					<stateid>11</stateid>
				</possiblestate>
			</possiblestates>
		</state>
		<state>
			<statename>Cancel</statename>
			<stateid>11</stateid>
			<possiblestates>
				<possiblestate>
						<statename>PartialApplication</statename>
						<stateid>7</stateid>
				</possiblestate>
			</possiblestates>
		</state>
		<state>
			<statename>Apporved</statename>
			<stateid>9</stateid>
			<possiblestates>
				<possiblestate>
					<statename>OnHold</statename>
					<stateid>10</stateid>
				</possiblestate>
				<possiblestate>
					<statename>Closed</statename>
					<stateid>12</stateid>
				</possiblestate>
			</possiblestates>
		</state>
		<state>
			<statename>OnHold</statename>
			<stateid>10</stateid>
			<possiblestates>
				<possiblestate>
					<statename>Apporved</statename>
					<stateid>9</stateid>
				</possiblestate>
				<possiblestate>
					<statename>Closed</statename>
					<stateid>12</stateid>
				</possiblestate>
			</possiblestates>
		</state>
		<state>
			<statename>Closed</statename>
			<stateid>12</stateid>
		</state>
	</stateConfiguration>
</statemaps>

=== mifos/1.4.x/application/src/main/resources/org/mifos/framework/util/resources/stateMachine/StateMachine_loan.xml
<?xml version="1.0" encoding="UTF-8"?>
<statemaps xmlns="http://www.aditi.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.aditi.com StateMachine.xsd ">
	<stateConfiguration configurationName="configuration 1">
		<state>
			<statename>PartialApplication</statename>
			<stateid>1</stateid>
			<possiblestates>
				<possiblestate>
					<statename>PendingApproval</statename>
					<stateid>2</stateid>
				</possiblestate>
				<possiblestate>
					<statename>Cancel</statename>
					<stateid>10</stateid>
				</possiblestate>
			</possiblestates>
		</state>
		<state>
			<statename>Cancel</statename>
			<stateid>10</stateid>
		</state>
		<state>
			<statename>PendingApproval</statename>
			<stateid>2</stateid>
			<possiblestates>
				<possiblestate>
					<statename>PartialApplication</statename>
					<stateid>1</stateid>
				</possiblestate>
				<possiblestate>
					<statename>Apporved</statename>
					<stateid>3</stateid>
				</possiblestate>
				<possiblestate>
					<statename>DBtoLoanOfficer</statename>
					<stateid>4</stateid>
				</possiblestate>
				<possiblestate>
					<statename>Cancel</statename>
					<stateid>10</stateid>
				</possiblestate>
			</possiblestates>
		</state>
		<state>
			<statename>Apporved</statename>
			<stateid>3</stateid>
			<possiblestates>
				<possiblestate>
					<statename>DBtoLoanOfficer</statename>
					<stateid>4</stateid>
				</possiblestate>
				<possiblestate>
					<statename>Cancel</statename>
					<stateid>10</stateid>
				</possiblestate>
			</possiblestates>
		</state>
		<state>
			<statename>DBtoLoanOfficer</statename>
			<stateid>4</stateid>
			<possiblestates>
				<possiblestate>
					<statename>Cancel</statename>
					<stateid>10</stateid>
				</possiblestate>
			</possiblestates>
		</state>
		<state>
			<statename>ActiveInGoodStanding</statename>
			<stateid>5</stateid>
			<possiblestates>
				<possiblestate>
					<statename>Rescheduled</statename>
					<stateid>8</stateid>
				</possiblestate>
				<possiblestate>
					<statename>WrittenOff</statename>
					<stateid>7</stateid>
				</possiblestate>
			</possiblestates>
		</state>
		<state>
			<statename>ActiveInBadStanding</statename>
			<stateid>9</stateid>
			<possiblestates>
				<possiblestate>
					<statename>Rescheduled</statename>
					<stateid>8</stateid>
				</possiblestate>
				<possiblestate>
					<statename>WrittenOff</statename>
					<stateid>7</stateid>
				</possiblestate>
			</possiblestates>
		</state>
	</stateConfiguration>

	<stateConfiguration configurationName="configuration 2">
		<state>
			<statename>PartialApplication</statename>
			<stateid>1</stateid>
			<possiblestates>
				<possiblestate>
					<statename>Apporved</statename>
					<stateid>3</stateid>
				</possiblestate>
				<possiblestate>
					<statename>Cancel</statename>
					<stateid>10</stateid>
				</possiblestate>
			</possiblestates>
		</state>
		<state>
			<statename>Cancel</statename>
			<stateid>10</stateid>
		</state>
		<state>
			<statename>Apporved</statename>
			<stateid>3</stateid>
			<possiblestates>
				<possiblestate>
					<statename>DBtoLoanOfficer</statename>
					<stateid>4</stateid>
				</possiblestate>
				<possiblestate>
					<statename>Cancel</statename>
					<stateid>10</stateid>
				</possiblestate>
			</possiblestates>
		</state>
		<state>
			<statename>DBtoLoanOfficer</statename>
			<stateid>4</stateid>
			<possiblestates>
				<possiblestate>
					<statename>Cancel</statename>
					<stateid>10</stateid>
				</possiblestate>
			</possiblestates>
		</state>
		<state>
			<statename>ActiveInGoodStanding</statename>
			<stateid>5</stateid>
			<possiblestates>
				<possiblestate>
					<statename>Rescheduled</statename>
					<stateid>8</stateid>
				</possiblestate>
				<possiblestate>
					<statename>WrittenOff</statename>
					<stateid>7</stateid>
				</possiblestate>
			</possiblestates>
		</state>
		<state>
			<statename>ActiveInBadStanding</statename>
			<stateid>9</stateid>
			<possiblestates>
				<possiblestate>
					<statename>Rescheduled</statename>
					<stateid>8</stateid>
				</possiblestate>
				<possiblestate>
					<statename>WrittenOff</statename>
					<stateid>7</stateid>
				</possiblestate>
			</possiblestates>
		</state>
	</stateConfiguration>
	<stateConfiguration configurationName="configuration 3">
		<state>
			<statename>PartialApplication</statename>
			<stateid>1</stateid>
			<possiblestates>
				<possiblestate>
					<statename>PendingApproval</statename>
					<stateid>2</stateid>
				</possiblestate>
				<possiblestate>
					<statename>Cancel</statename>
					<stateid>10</stateid>
				</possiblestate>
			</possiblestates>
		</state>
		<state>
			<statename>Cancel</statename>
			<stateid>10</stateid>
		</state>
		<state>
			<statename>PendingApproval</statename>
			<stateid>2</stateid>
			<possiblestates>
				<possiblestate>
					<statename>PartialApplication</statename>
					<stateid>1</stateid>
				</possiblestate>
				<possiblestate>
					<statename>Apporved</statename>
					<stateid>3</stateid>
				</possiblestate>
				<possiblestate>
					<statename>Cancel</statename>
					<stateid>10</stateid>
				</possiblestate>
			</possiblestates>
		</state>
		<state>
			<statename>Apporved</statename>
			<stateid>3</stateid>
			<possiblestates>
				<possiblestate>
					<statename>Cancel</statename>
					<stateid>10</stateid>
				</possiblestate>
			</possiblestates>
		</state>
		<state>
			<statename>ActiveInGoodStanding</statename>
			<stateid>5</stateid>
			<possiblestates>
				<possiblestate>
					<statename>Rescheduled</statename>
					<stateid>8</stateid>
				</possiblestate>
				<possiblestate>
					<statename>WrittenOff</statename>
					<stateid>7</stateid>
				</possiblestate>
			</possiblestates>
		</state>
		<state>
			<statename>ActiveInBadStanding</statename>
			<stateid>9</stateid>
			<possiblestates>
				<possiblestate>
					<statename>Rescheduled</statename>
					<stateid>8</stateid>
				</possiblestate>
				<possiblestate>
					<statename>WrittenOff</statename>
					<stateid>7</stateid>
				</possiblestate>
			</possiblestates>
		</state>
	</stateConfiguration>
	<stateConfiguration configurationName="configuration 4">
		<state>
			<statename>PartialApplication</statename>
			<stateid>1</stateid>
			<possiblestates>
				<possiblestate>
					<statename>Apporved</statename>
					<stateid>3</stateid>
				</possiblestate>
				<possiblestate>
					<statename>Cancel</statename>
					<stateid>10</stateid>
				</possiblestate>
			</possiblestates>
		</state>
		<state>
			<statename>Cancel</statename>
			<stateid>10</stateid>
		</state>
		<state>
			<statename>Apporved</statename>
			<stateid>3</stateid>
			<possiblestates>
				<possiblestate>
					<statename>Cancel</statename>
					<stateid>10</stateid>
				</possiblestate>
			</possiblestates>
		</state>
		<state>
			<statename>ActiveInGoodStanding</statename>
			<stateid>5</stateid>
			<possiblestates>
				<possiblestate>
					<statename>Rescheduled</statename>
					<stateid>8</stateid>
				</possiblestate>
				<possiblestate>
					<statename>WrittenOff</statename>
					<stateid>7</stateid>
				</possiblestate>
			</possiblestates>
		</state>
		<state>
			<statename>ActiveInBadStanding</statename>
			<stateid>9</stateid>
			<possiblestates>
				<possiblestate>
					<statename>Rescheduled</statename>
					<stateid>8</stateid>
				</possiblestate>
				<possiblestate>
					<statename>WrittenOff</statename>
					<stateid>7</stateid>
				</possiblestate>
			</possiblestates>
		</state>
	</stateConfiguration>
</statemaps>

=== mifos/1.4.x/application/src/main/resources/org/mifos/framework/util/resources/stateMachine/StateMachine_center.xml
<?xml version="1.0" encoding="UTF-8"?>
<statemaps xmlns="http://www.aditi.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.aditi.com StateMachine.xsd ">
	<stateConfiguration configurationName="configuration 1">
		<state>
			<statename>Active</statename>
			<stateid>13</stateid>
			<possiblestates>
				<possiblestate>
						<statename>Inactive</statename>
						<stateid>14</stateid>
				</possiblestate>
			</possiblestates>
		</state>
		<state>
			<statename>Inactive</statename>
			<stateid>14</stateid>
			<possiblestates>
				<possiblestate>
					<statename>Active</statename>
					<stateid>13</stateid>
				</possiblestate>
			</possiblestates>
		</state>
	</stateConfiguration>
</statemaps>
